matrix:
  include:
    - os: linux
      dist: trusty
language: csharp
mono: latest
dotnet: 2.1.105
before_install:
  - sudo apt-get install p7zip-full nuget
  - if [ "$REDISTPASSWORD" != "" ] ; then cd Redist ; wget -q https://github.com/surban/managedCuda-redist/releases/download/v9.1.3/redist.7z ; 7z x -p$REDISTPASSWORD -y redist.7z ; cd .. ; fi
script: 
  - unset DOTNET_CLI_TELEMETRY_OPTOUT
  - if [ "$REDISTPASSWORD" = "" ] ; then dotnet build -c Release ; fi
  - if [ "$REDISTPASSWORD" != "" ] ; then dotnet pack -c Release ; fi
  - if [ "$TRAVIS_BRANCH" = "master" ] ; then travis_wait 200 bash Docs/build.sh ; fi
after_success:
  - dotnet nuget push -s https://api.nuget.org/v3/index.json -k $NUGETKEY 'Packages/Release/*.nupkg' || true 
deploy:
  - provider: pages
    local-dir: Docs/_site
    skip-cleanup: true
    target-branch: gh-pages
    github-token: $GITHUB_TOKEN  
    keep-history: true
    on:
      branch: master
  